name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True
    - name: Run XUnit Tests
      run: dotnet test XUnit.UnitTests/XUnit.UnitTests.csproj
      continue-on-error: true
    - name: Run NUnit Tests
      run: dotnet test NUnit.UnitTests/NUnit.UnitTests.csproj
      continue-on-error: true
    - name: Run MsTest Tests
      run: dotnet test MsTest.UnitTests/MsTest.UnitTests.csproj
      continue-on-error: true
